feat: Add Empty Response Handling via CLI flag
kalbasit/signal-api-receiver pull request #52
Opened 2024-12-31 01:30 UTC by leptoquark1

Adds a flag which changes the default response of the route `/receive/pop` if there are no messages in the queue. Instead of an empty body and the HTTP status code 204, the HTTP status code 200 (same as if there was a message in the queue) and the body ‘{}’ (empty JSON object) are now used when this flag is set.

The purpose of this is to avoid warnings being raised by Home-Assistants Rest Integration, which expects a valid JSON object in the body.

2024-12-31 04:16 UTC, kalbasit commented
Oh, I was not aware that home-assistant was logging a warning due to the 204; Can you please paste the warning you got? If this is causing a warning then we should forgo the 204 and return `{}` by default. Thanks for pointing this out!

2024-12-31 04:20 UTC, kalbasit requested changes
Oh you're right, I'm seeing this in my logs too

```
2024-12-30 20:18:18.632 WARNING (MainThread) [homeassistant.components.rest.util] Empty reply found when expecting JSON data
```

Do you mind changing the PR so this is the default behavior? Please get rid of the flag, there's no need to have the option to return 204 if it's generating warnings.

2024-12-31 09:23 UTC, leptoquark1 commented
> Oh you're right, I'm seeing this in my logs too
> 
> ```
> 2024-12-30 20:18:18.632 WARNING (MainThread) [homeassistant.components.rest.util] Empty reply found when expecting JSON data
> ```
> 
> Do you mind changing the PR so this is the default behavior? Please get rid of the flag, there's no need to have the option to return 204 if it's generating warnings.

Sure thing. This will be a breaking change though..

2024-12-31 09:59 UTC, kalbasit commented
> > Do you mind changing the PR so this is the default behavior? Please get rid of the flag, there's no need to have the option to return 204 if it's generating warnings.
> 
> Sure thing. This will be a breaking change though..

I don't think it'll break existing installs since HA seems to handle it fine with a warning anyways.

2025-01-01 05:53 UTC, kalbasit commented on pkg/server/server.go
> +		}
isn't cheaper to do something like this?

```suggestion
		if err := w.Write([]byte("{}")); err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
```

2025-01-02 08:41 UTC, leptoquark1 commented
@kalbasit I noticed that my solution still produced warnings but now a different when parsing attributes in envelope. Please check my fixup suggestion at [2e012a3](https://github.com/kalbasit/signal-api-receiver/commit/2e012a31c2a041efefba678d5b5b49194978cfc6)

2025-01-02 08:51 UTC, kalbasit commented
@leptoquark1 can you share how you're parsing the response in your home assistant?

2025-01-09 21:21 UTC, leptoquark1 commented
> @leptoquark1 can you share how you're parsing the response in your home assistant?

Yeah sure, sorry for the delay.

<details>
<summary>rest.yaml</summary>

```yaml
rest:
  - resource: "http://broker.srv.local:8105/receive/pop"
    method: GET
    scan_interval: 15
    timeout: 5
    verify_ssl: false
    sensor:
      - name: Signal receipt event received
        icon: mdi:message-badge-outline
        value_template: "{{ iif(value_json.envelope.receiptMessage, 'on', 'off', None) }}"
        json_attributes_path: "$.envelope.receiptMessage"
        json_attributes:
          - when
          - isDelivery
          - isRead
          - isViewed
          - timestamps
      - name: Signal typing event received
        icon: mdi:message-processing-outline
        value_template: "{{ iif(value_json.envelope.typingMessage, 'on', 'off', None) }}"
        json_attributes_path: "$.envelope.typingMessage"
        json_attributes:
          - action
          - timestamp
      - name: Signal data event received
        icon: mdi:message-fast-outline
        value_template: "{{ iif(value_json.envelope.dataMessage, 'on', 'off', None) }}"
        json_attributes_path: "$.envelope.dataMessage"
        json_attributes:
          - message
          - expiresInSeconds
          - viewOnce
          - mentions
          - groupInfo
          - quote
          - timestamp
      # availability: "{{ value_json.envelope.dataMessage is defined and value_json.envelope.dataMessage is not none }}"
```

</details>

2025-07-19 23:55 UTC, quenthal commented
Is this possible to handle in the template side on home assistant? or only way to avoid logspam is filter rest.util?

2026-03-15 16:31 UTC, leptoquark1 commented
> @leptoquark1 Is this PR still the best way to solve this issue? Perhaps we should open an issue to track it and possibly close this one in favor of a better approach?

The main issue here is that request to route "/receive/pop" returns no body in response when no message in queue.

https://github.com/leptoquark1/signal-api-receiver/blob/8cc7c34/pkg/server/server.go#L102-106

Since the RESTful integration can only be configured to a limited extent via YAML. It always expects a JSON in the body, which it attempts to parse and then generates that warning:

> [homeassistant.components.rest.util] Empty reply found when expecting JSON data

Additionally, if body would only fallback to empty an JSON object (`{}`) but in Home Assistant you try to parse attributes ([Example Config](https://github.com/kalbasit/signal-api-receiver/pull/52#issuecomment-2581270273) [Docs](https://www.home-assistant.io/integrations/sensor.rest#json_attributes)) from the nested "Envelope" object, it produce the very same warning. So the minimal fix to solve this issue for most use cases would be some like [2e012a3](https://github.com/kalbasit/signal-api-receiver/commit/2e012a31c2a041efefba678d5b5b49194978cfc6#diff-104a11712684e520f0affa95e6a053faeb713306a10f69ee99b9729cc9dd1996R112)

I'd say this is still relevant. However, I can't think of any better solution than the current one.

2026-03-15 17:50 UTC, closed without merging